server:
  port: 8083

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:h2:mem:admindb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

logging:
  level:
    com.api.adminservice: DEBUG
    org.springframework.security: DEBUG 